# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1c09979ac8e707bb4636ba1b725f10ea72e28ad39829719273096a7b82f1505b908ab26c5aca86aac116b176090b237ee56c6024450898e30d760b90dd67fea

test:
  secret_key_base: 33bcecd6a8ff1c611d2596b07de3469b67830182c12b43ce2284d101def7b05b303bf8fa50080ac75980a540f8179ce388937f1a4a3a55ddb12374c6e15f8d82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
